### ISSUE TITLE
Fotos

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#1]
A la columna Foto, tanto del socio principal como del dependiente se envía la ruta junto con el nombre del archivo y extensión: Img\100000-1.png. Verificar que hace falta para que el site muestre la foto, si es del script o del mismo site.

![screen shot 2015-04-16 at 11 31 06](https://cloud.githubusercontent.com/assets/6236683/7185982/1ab537e8-e42c-11e4-890e-cc91d3d2c8bc.png)

**Comment by vsalomons** [comment]
Te pone la foto default cuando no la encuentra?
esa ruta img\xxxx.png estamos hablando dentro del site osea
wwwroot\site\img\xxxx.png
para q la url en internet sea 
http:\www.algo.com\img\xxxx.png

no lo revise en el código .... recuerdo q verifico si puedo cargar la imagen y si hay una excepción pongo la default

quizá mi error es tratar de abrir la hubicacion asi tal cual la mandes entonces nunca podre abrir algo "img\xxxx.png"
probamos si me mandas la ruta completa http:\www.algo.com\img\xxxx.png

**Comment by antwainvonD** [comment]
Cerrado el tema de las fotos, ahora las carga sin problema, dejamos la ruta física en la configuración

**Comment by vsalomons** [comment]
te actualice mi sql para un inicio de la logica del ingreso
te mando esta compilacion q seguin ya ingresa algo en esa estructura
​nos vemos a las 930pm​

**Comment by vsalomons** [comment]
esta esta mucho mejor

On Tue, Apr 21, 2015 at 10:17 AM, antwain vonD notifications@github.com
wrote:

> Closed #1 https://github.com/antwainvonD/gitControlAccesos/issues/1.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/antwainvonD/gitControlAccesos/issues/1#event-286322525
> .

## 

www.vsalomons.com

Vitor Salomons
