### ISSUE TITLE
Agregar el campo Area que visita

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#10]
- Se me pasó comentarte que solicitaron agregar el campo **Area** que visitan Socios, Dependientes e Invitados
- Este campo habrá que agregarlo en el link de Socios y Dependientes.
- Debe ser un Listbox esta es la sentencia: _SELECT Elemento FROM SoporteElemento_ y solo debe aceptar los valores de la lista

**Comment by vsalomons** [comment]
Para la pantalla individual se tendra un combo... 
como se realizara la seleccion para la pantalla de los invitados , todos a la misma area o en particular cada uno. 
lo podemos poner en un sp este select para q no quede nada en duro en el sistema?

**Comment by antwainvonD** [comment]
Es correcto, todos irán a la misma area. Si quieres puedes ver un pequeño ejemplo en el issue #13

**Comment by antwainvonD** [comment]
Validado el campo área
