### ISSUE TITLE
Ingreso de invitados escenario No.2

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#12]
El proceso de ingreso de invitados, tiene 2 escenarios:
1. Cuando el invitado y socio entran al mismo tiempo. Este proceso está cubierto con la selección de checks y botón Ingresar Todos.
2. Cuando el invitado llega después del socio, es decir, el socio llega primero e informa que un invitado vendrá, debe dejar los datos completos ya sea en la garita o en la recepción del club.

Para éste segundo escenario, se deberán seguir los siguientes pasos:
- [x] En cuanto llegue el invitado a la garita, deberá proporcionar el número de socio (de quien lo invitó).
- [x] El vigilante deberá buscar el número de socio y posterior a esto, seleccionar el menú _Dependientes e Invitados_
- [x] Deberá buscar si existe el invitado, en caso de que no exista, escribirá el nombre y la cédula
- [x] Finalmente dará click al `link` que tiene el nombre del invitado:
- [x] Se muestra el link de _Socio_: **Aquí se requieren las modificaciones**
  - La pantalla se muestra de la siguiente forma: Será necesario colocar el nombre del Invitado en lugar de la Cédula y frente a la leyenda socio: colocar el número de cédula
    ![screen shot 2015-04-28 at 10 48 08](https://cloud.githubusercontent.com/assets/6236683/7373962/286335d0-ed95-11e4-89a6-6a5b0f78b19c.png)
  - Al presionarl el botón **Ingreso**, no está enviando el sp _MobileAcceso_NuevoRegistro_

**Comment by vsalomons** [comment]
Modificado para probar los textos

El boton realice pruebas y si lo hace... 
que otra cosa haces para replicar que no funcione

**Comment by antwainvonD** [comment]
Hmm, no se que podría ser, igual tema de chaché o algo. Esperaré a que me envíes el nuevo release con las modificaciones y vuelvo a verificar.

**Comment by antwainvonD** [comment]
Te mando un pequeño video del proceso cuando sucede esto, lo subí a dropbox, espero lo peudas ver y verificar

**Comment by vsalomons** [comment]
Ya vi el video , te mando la version que ya lo hace en la pantalla incial

**Comment by antwainvonD** [comment]
Perfecto, validado, ya ingresa al invitado solo
