### ISSUE TITLE
Ultimos 10, bug de caché

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#14]
Al parecer éste tema ya lo habías detectado, que es, después de generar una entrada, y mostrar los ultimos 10, no muestra el registro actualizado.

**Comment by vsalomons** [comment]
registras una entrada entonces te borra todo.
luego cambias a tu historial y según yo si aparece el ultimo registro.
pero al regresar al socio te pone la pantalla en blanco

**Comment by antwainvonD** [comment]
Que onda bro, te mando un video al dropbox para que puedas ver el proceso, como que no refresca la página.

**Comment by antwainvonD** [comment]
validado, perfect
