### ISSUE TITLE
Ingreso de invitados

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#15]
Acaban de solicitar saber con que socio el invitado ingresó, es decir, el día de hoy el invitado ingresa siempre con el socio `1` (**100000-1**), independientemente de si entró con el _hijo_ `5` (**100000-5**) o la hija `4` (**100000-4**).

Preguntando el escenario en el que 2 socios entren con 1 invitado, o _n_ socios entran con _n_ invitados. _¿A cual socio se cargará la entrada de dicho invitado?_ ellos responden:
A cualquiera de los 2, así que para este caso se podría enviar al sp, el último de los socios que entró.

NOTA: Creo que este tema es un issue algo complicado ya que necesitarías ingresar primero a los socios y al final a los invitados, esto con el fin de saber que variable se le envía como _@Cliente_ (ya que siempre se manda 100000**-1**

**Comment by vsalomons** [comment]
Se me ocurre casi casi que podríamos anular el botón de ingresar  la pantalla inicial para q siempre lo hagan en la de invitados & dependientes
seleccionando socio y invitado.

**Comment by antwainvonD** [comment]
cerrado, se queda como está
