### ISSUE TITLE
Cambio de numérico a alfanumércio en el textbox de búsqueda de socio

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#3]
![screen shot 2015-04-24 at 17 49 51](https://cloud.githubusercontent.com/assets/6236683/7330304/f4d466a2-eab1-11e4-9683-6ea8304d9598.png)

**Comment by vsalomons** [comment]
modificado para q acepte letras tambien

**Comment by antwainvonD** [comment]
Probado y verificado
