### ISSUE TITLE
Búsqueda de socios sin guiones

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#4]
Dejar la lógica de los guiones a los sp's, ya que cuando se busca un socio sin guión no muestra nada el site, aunque el sp si trae datos.
![screen shot 2015-04-24 at 18 46 36](https://cloud.githubusercontent.com/assets/6236683/7330337/7d4adfde-eab2-11e4-92ba-0996434fc180.png)

**Comment by vsalomons** [comment]
aceptando letras y sin verificar la aparecicion de guion en  la clave

**Comment by antwainvonD** [comment]
Probado y verificado
