### ISSUE TITLE
Debuggear el sp: MobileAcceso_NuevoRegistro

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#5]
*Toño
1. Al momento de insertar el invitado pierde el nombre del mismo y no lo inserta

**Comment by vsalomons** [comment]
no lo he replicado

**Comment by antwainvonD** [comment]
Encontré el error, el problema era de lógica, ya que sólo se buscaba el nombre en la tabla de MobileAcceso_Invitados que se llena al momento de agregar un nuevo invitado, sin embargo si no se escribe ningún nuevo invitado (no había datos en esa tabla).

Ahora se va a buscar el nombre dentro tanto de la tabla MobileAcceso_Invitados como de MobileAcceso_Movimientos.
