### ISSUE TITLE
Redireccionar la URL de login al terminar el timeout

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#7]
Cuando pasan los 5 minutos del webconfig manda un mensaje: Error Loading Page

![screen shot 2015-04-24 at 19 22 15](https://cloud.githubusercontent.com/assets/6236683/7330624/87ddb502-eab7-11e4-9dde-6f041dc6e9b6.png)

**Comment by vsalomons** [comment]
Modificado y en espera de probar en la operacion

**Comment by antwainvonD** [comment]
Se verificaron los siguientes escenarios:
- [x] 1. Cuando estoy posicionado en la pantalla de Dependientes, llegan los 5 mins de inactividad y doy click al link de Ultimos 10, envía el mensaje: **Error Loading Page**
- [x] 2. Cuando estoy posicionado en la pantalla de Dependientes, llegan los 5 mins de inactividad y doy click al link de Socios, manda el mensaje **Error Loading Page**
- [x] 3. Cuando estoy posicionado en la pantalla de Ultimos 10, llegan los 5 mins de inactividad y doy click al link de Socios, manda el mensaje **Error Loading Page**
- [x] 4. Cuando estoy posicionado en la pantalla de Socios, llegan los 5 mins de inactiviad y doy click al link de Ultimos 10, envía el mensaje: **Error Loading Page**
- [x] 5. Cuando estoy posicionado en la pantalla de Ultimos 10, llegan los 5 mins de inactiviad y doy click al link de Dependientes redirecciona bien.
- [x] 6. Cuando estoy posicionado en la pantalla de Socios, llegan los 5 mins de inactiviad y doy click al link de Dependientes redirecciona bien.
- [x] 7. Cuando estoy posicionado en la pantalla de Socios, llegan los 5 mins de inactiviad y doy click al botón de buscar, envía el mensaje: **Error Loading Page**
- [x] 8. Cuando estoy posicionado en la pantalla de Socios, llegan los 5 mins de inactiviad y doy click al botón de limpiar redirecciona bien.

**Comment by antwainvonD** [comment]
Por casualidad hice un ejemplo extra, que es cuando dejas la página de los _Ultimos 10_ y llega el timeout, si por alguna razón presionas `F5` o actualizas la página, manda el siguiente mensaje:

![2015-05-06_16-34-07](https://cloud.githubusercontent.com/assets/6236683/7504203/029246b4-f40e-11e4-9422-948d906ea5fd.png)

**Comment by antwainvonD** [comment]
Te estoy mandando vía dropbox los videos.

Para cada punto estoy generando un video con el título: `TimeOut` seguido del _número_ de punto que el video representa, es decir, el video **TimeOut_1.mp4** hace referencia al **primer** punto del issue, el _TimeOut_2.mp4_ hace referencia al _segundo_ punto y así sucesivamente.
- El punto No. 2 queda validado.
- El punto No. 3 queda validado.
- Los puntos No. 5 y 6 redireccionan de forma correcta
- Se agregan los puntos No. 7 y 8, el punto 8 funciona de forma correcta, el 7 no.

**Comment by vsalomons** [comment]
probados los puntos. restantes
que browser usara el cliente finalmente
firefox o IE?

**Comment by antwainvonD** [comment]
En la PC ocuparán IE y en la tablet sería Safari o Chrome (depende la tablet).

Validado el Punto No. 1
Validado el Punto No. 4
Validado el Punto No. 7
