### ISSUE TITLE
Logotipos

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#8]
1. Cambiar al .png el logo del cub de golf (logo24).
2. Recorrer el logo a la parte derecha
3. Agregar el logo de intelisis en la parte inferior izquierda con la leyenda **Powered by** _debajo_

**Comment by antwainvonD** [comment]
Algo así deberían quedar los logos. Si necesitas las imágenes me dices.
![screen shot 2015-04-28 at 13 55 59](https://cloud.githubusercontent.com/assets/6236683/7378209/67289cc6-edb1-11e4-80d1-e6440c79be52.jpg)

**Comment by vsalomons** [comment]
Modificado en la pantalla de socio

**Comment by vsalomons** [comment]
TEner cuidado de remplazar los files de img con la extension png

**Comment by antwainvonD** [comment]
Va, en cuanto me pases el .rar hago las pruebas. Agregaría yo esos .png's que mandé en el comment principal

**Comment by antwainvonD** [comment]
Listo, quedaron bien los logotipos, las modificaciones que hice sobre mobile.aspx te las mando por correo.
