### ISSUE TITLE
Limpiar la foto, al presionar el botón Limpiar

### ISSUE THREAD

**Issue by antwainvonD** [antwainvonD/gitControlAccesos#9]
Limpiar la foto, al presionar el botón Limpiar

**Comment by vsalomons** [comment]
Pondra la imagen de un hombre clearM.jpg
Por cierto la de clearF.jpg puede ser para mujer si es q el socio no tiene foto y tiene sexo femenino

**Comment by antwainvonD** [comment]
Validado, al momento de limpiar ya limpia la foto también.

Un par de dudas, por lo que comentas, dependiendo el sexo manda una foto u otra, sin embargo, en el sp: MobileAcceso_CteData, siempre se le manda 0 al parámetro **sexo**.
- ¿Cuales serían los valores para cada sexo?

Dentro del código de _mobile.aspx_ traes implícito la llamada a la imagen "~/Img/clearM.jpg"
- ¿Dentro del jquery tienes el cambio de imagen? del clearM al clearF

NOTA: Ambas fotos son iguales, si queremos dar este efecto necesitamos que clearF.jpg sea de una mujer. _Posiblemente no sea necesario hacer esta modificación, es decir, si se hace adelante, pero no es un tema que detenga la entrega y operación, podemos omitirlo y agregarlo en otro release_

**Comment by antwainvonD** [comment]
Es más voy a cerrar éste issue, la vdd no es necesario que hagamos este cambio, jeje
